### ISSUE TITLE
The __pycache__ folder should not be in git

### ISSUE THREAD

**Issue by szabgab** [zguillez/python-toolz#1]
It is a generated folder with files specific to the current version of Python

**Comment by zguillez** [comment]
removed! thanks!

**Comment by szabgab** [comment]
Hi @zguillez 
I received a lot of value from the open source work of others. Opening this issue was my way of passing on a tiny bit of good deed to someone else. I am trying now to encourage more people, you too, to find other project(s) and make a small contribution there. See this issue explaining my reasoning further: https://github.com/OSDC-Code-Maven/OSDC-Code-Maven.github.io/issues/5
